# -*- coding: utf-8 -*-
"""HW4_1_6231332921.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sQZRpYwHXajdLkA-oskQtnFYKmPVQIdr
"""

import cv2
import imutils
import numpy as np
from matplotlib import pyplot as plt
# Import library here


def rotated(image, angle):
  return imutils.rotate(image, angle=angle)

# Add other augmentation functions here
def blur(image, size):
 return cv2.blur(image,(size,size))

def mirror(image):
  return cv2.flip(image, 1);
    
def gamma(image, gamma):
	invGamma = 1.0 / gamma
	table = np.array([((i / 255.0) ** invGamma) * 255
		for i in np.arange(0, 256)]).astype("uint8")
	return cv2.LUT(image, table)    

def salt_pepper(img):
    noise = np.random.randint(0,10,img.shape)==0
    img[noise] = np.random.random(noise.sum())*255
    return img

def sharp(img):
    kernel = np.array([[0,-1,0],
                   [-1,5,-1],
                   [0,-1,0]],dtype=np.float32)
    return cv2.filter2D(img,-1,kernel)

#main()
image = cv2.imread("kitty.jpg")
plt.imshow(image[:,:,::-1]);plt.title("original")
plt.show()

angle = 30
img_30 = rotated(image,angle)
plt.imshow(img_30[:,:,::-1]);plt.title("rotated by "+str(angle))
plt.show()

# show how to use your function and show your modified versions of the original image here
img = cv2.imread("samoy.jpg")


cv2.imwrite('img_01.png',rotated(img,30))
cv2.imwrite('img_02.png',blur(img,5))
cv2.imwrite('img_03.png',mirror(img))
cv2.imwrite('img_04.png',gamma(img,0.7))
cv2.imwrite('img_05.png',salt_pepper(img))
cv2.imwrite('img_06.png',sharp(img))